# Generated by Django 2.0.3 on 2018-03-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dym', '0001_initial'), ('dym', '0002_auto_20180324_2231'), ('dym', '0003_auto_20180324_2312'), ('dym', '0004_auto_20180324_2314'), ('dym', '0005_auto_20180324_2315')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Client name')),
                ('email', models.EmailField(max_length=254, verbose_name='Client email')),
                ('mobile', models.IntegerField(default=0, verbose_name='Client mobile number')),
                ('phone', models.IntegerField(default=0, verbose_name='Client phone number')),
                ('address', models.TextField(verbose_name='Client address')),
                ('gender', models.CharField(max_length=1, verbose_name='M/F')),
                ('join_date', models.DateTimeField(verbose_name='Join membership date')),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
                ('accumulates', models.IntegerField(default=0, verbose_name='Accumulated order price')),
                ('n_purchase_orders', models.IntegerField(default=0, verbose_name='number of purchase orders')),
                ('n_craft_orders', models.IntegerField(default=0, verbose_name='number of craft orders')),
                ('rank', models.IntegerField(default=0, verbose_name='VIP rank')),
                ('status', models.IntegerField(default=0, verbose_name='Client status')),
                ('tag', models.TextField(verbose_name='Tag/Note/Description')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Order begin date')),
                ('status', models.IntegerField(default=0, verbose_name='Order status')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dym.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='accumulates',
            field=models.IntegerField(default=0, verbose_name='累积消费'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateTimeField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='客户邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(verbose_name='加入会员日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.IntegerField(default=0, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='member',
            name='n_craft_orders',
            field=models.IntegerField(default=0, verbose_name='累积制作订单'),
        ),
        migrations.AlterField(
            model_name='member',
            name='n_purchase_orders',
            field=models.IntegerField(default=0, verbose_name='累积销售订单'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='座机'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='VIP等级'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(default=0, verbose_name='客户状态'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
