# Generated by Django 2.1 on 2018-08-11 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField(default=django.utils.timezone.now, verbose_name='订制日期')),
                ('ddate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='设计日期')),
                ('sdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='送厂日期')),
                ('edate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='预计完成日期')),
                ('adate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='实际完成日期')),
                ('producer', models.CharField(blank=True, max_length=128, null=True, verbose_name='制作方')),
                ('by', models.CharField(max_length=128, verbose_name='经手人')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='制作描述')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='InBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('kind', models.IntegerField(choices=[(0, '珍珠'), (1, '翡翠'), (2, '白玉'), (3, '彩宝'), (4, '钻石'), (5, '文玩'), (6, '素金'), (7, '古董珠宝'), (8, '瓷器'), (9, '裸链'), (999, '其他')], default=999, verbose_name='类别')),
                ('type', models.IntegerField(choices=[(0, '成品'), (1, '原石'), (2, '裸链'), (3, 'K金配件'), (4, '客带'), (5, '手工配件'), (6, '配石'), (7, '配件'), (8, '其他配件'), (999, '其他')], default=0, verbose_name='库存类型')),
                ('where', models.IntegerField(choices=[(0, '冬君'), (1, '店面'), (2, '设计师'), (3, '其他')], default=0, verbose_name='库号')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('qunit', models.CharField(blank=True, max_length=16, null=True, verbose_name='数量单位')),
                ('weight', models.IntegerField(default=0, verbose_name='重量')),
                ('wunit', models.CharField(blank=True, max_length=16, null=True, verbose_name='重量单位')),
                ('baseprice', models.IntegerField(default=0, verbose_name='单价')),
                ('saleprice', models.IntegerField(default=0, verbose_name='售价')),
                ('tweight', models.IntegerField(default=0, verbose_name='总重')),
                ('tprice', models.IntegerField(default=0, verbose_name='总价')),
                ('provider', models.CharField(blank=True, max_length=128, null=True, verbose_name='供应商')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='入库日期')),
                ('by', models.CharField(max_length=128, verbose_name='经手人')),
                ('length', models.CharField(blank=True, max_length=64, null=True, verbose_name='长度')),
                ('diameter', models.CharField(blank=True, max_length=64, null=True, verbose_name='直径度')),
                ('ktype', models.IntegerField(choices=[(0, '18K红'), (1, '18K黄'), (2, '18K白'), (3, 'PT950'), (4, 'PT900'), (5, 'PT850'), (6, '14K红'), (7, '14K黄'), (8, '14K白'), (9, '10K黄'), (10, '10K白'), (11, '24K'), (12, '925银'), (999, '其他'), (9999, '不适用')], default=9999, verbose_name='K金类别')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'permissions': (('canin', 'WR: Can add/change/delete inbound sheet'), ('viewbase', 'WR: Can access base price')),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('nick', models.CharField(max_length=64, verbose_name='昵称')),
                ('wechat', models.CharField(max_length=64, verbose_name='微信号')),
                ('source', models.IntegerField(choices=[(0, '其他'), (1, '会员介绍'), (2, '店面客人'), (3, '网络推广'), (4, '展会')], default=0, verbose_name='来源')),
                ('upstream', models.IntegerField(default=0, verbose_name='介绍人')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('mobile', models.IntegerField(default=0, unique=True, verbose_name='手机')),
                ('phone', models.IntegerField(blank=True, default=0, null=True, verbose_name='座机')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('gender', models.IntegerField(choices=[(0, '美女'), (1, '帅哥')], default=0, verbose_name='性别')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='加入会员日期')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('accumulates', models.IntegerField(default=0, verbose_name='累积消费')),
                ('ds_acc', models.IntegerField(default=0, verbose_name='下线累积消费')),
                ('n_purchase_orders', models.IntegerField(default=0, verbose_name='累积销售订单')),
                ('n_craft_orders', models.IntegerField(default=0, verbose_name='累积制作订单')),
                ('rank', models.IntegerField(choices=[(0, '普通会员'), (1, '高级会员'), (2, '至尊会员')], default=0, verbose_name='VIP等级')),
                ('status', models.IntegerField(choices=[(0, '已退'), (1, '活跃')], default=1, verbose_name='会员状态')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='照片')),
            ],
            options={
                'permissions': (('edit_member', 'Can add/change/delete members'),),
            },
        ),
        migrations.CreateModel(
            name='OutBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='出库日期')),
                ('by', models.CharField(max_length=128, verbose_name='经手人')),
                ('price', models.IntegerField(default=0, verbose_name='售价')),
                ('people', models.CharField(blank=True, max_length=128, null=True, verbose_name='客户名（VIP输入手机可关联）')),
                ('payment', models.IntegerField(choices=[(0, '现金'), (1, '信用卡'), (2, '支付宝'), (3, '微信'), (9, '其他')], default=0, verbose_name='付款方式')),
                ('cost', models.IntegerField(default=0, verbose_name='生产费用')),
                ('producer', models.CharField(blank=True, max_length=128, null=True, verbose_name='制作商')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('recraft', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否重新制作')),
                ('type', models.IntegerField(choices=[(0, '未限定'), (1, '销售'), (2, '生产')], default=0, verbose_name='出库类型')),
                ('craft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.CraftSheet')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.Member')),
            ],
            options={
                'permissions': (('canout', 'WR: Can operate on outbound sheet'),),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remains', models.IntegerField(default=0, verbose_name='剩余')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '已出库'), (2, '找不到了>.<')], default=0, verbose_name='状态')),
                ('discount', models.IntegerField(default=100, verbose_name='折扣')),
                ('bestsale', models.IntegerField(default=0, verbose_name='特价')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('inb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.InBound')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/store', verbose_name='照片')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.Store')),
            ],
        ),
        migrations.AddField(
            model_name='outbound',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.Store'),
        ),
    ]
