# Generated by Django 2.0.3 on 2018-03-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='命名')),
                ('kind', models.TextField(verbose_name='种类')),
                ('type', models.IntegerField(default=0, verbose_name='（原材料/配件/成品/客带）')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='客户姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='客户邮箱')),
                ('mobile', models.IntegerField(default=0, verbose_name='手机')),
                ('phone', models.IntegerField(default=0, verbose_name='座机')),
                ('address', models.TextField(verbose_name='地址')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('join_date', models.DateTimeField(verbose_name='加入会员日期')),
                ('birthday', models.DateTimeField(verbose_name='生日')),
                ('accumulates', models.IntegerField(default=0, verbose_name='累积消费')),
                ('n_purchase_orders', models.IntegerField(default=0, verbose_name='累积销售订单')),
                ('n_craft_orders', models.IntegerField(default=0, verbose_name='累积制作订单')),
                ('rank', models.IntegerField(default=0, verbose_name='VIP等级')),
                ('status', models.IntegerField(default=1, verbose_name='客户状态')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='amber/static/portraits', verbose_name='照片')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='Order print id')),
                ('create_date', models.DateTimeField(verbose_name='Order begin date')),
                ('status', models.IntegerField(default=0, verbose_name='Order status')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amber.Member')),
            ],
        ),
    ]
