# Generated by Django 2.0.3 on 2018-04-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='照片'),
        ),
    ]
