# Generated by Django 2.0.3 on 2018-04-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0002_auto_20180415_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', '美女'), ('M', '帅哥')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '高级会员'), (2, '至尊会员')], default=0, verbose_name='VIP等级'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(0, '已退'), (1, '活跃')], default=1, verbose_name='客户状态'),
        ),
    ]
