# Generated by Django 2.1 on 2018-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0002_auto_20180929_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='seq',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='kind',
            field=models.IntegerField(choices=[(0, '珍珠'), (1, '翡翠'), (2, '白玉'), (3, '彩宝'), (4, '钻石'), (5, '文玩'), (6, '素金'), (7, '古董珠宝'), (8, '瓷器'), (9, '裸链'), (10, '珊瑚'), (11, '玉石'), (12, '半宝'), (999, '其他')], default=999, verbose_name='类别'),
        ),
    ]
