# Generated by Django 2.0.3 on 2018-04-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0003_auto_20180415_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=32, verbose_name='客户姓名'),
        ),
    ]
