# Generated by Django 2.1 on 2018-12-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0003_auto_20181202_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amber.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amber.InBound'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amber.Store'),
        ),
    ]
