# Generated by Django 2.0.3 on 2018-04-21 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0004_auto_20180421_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 4, 12, 26, 252160, tzinfo=utc), verbose_name='加入会员日期'),
        ),
    ]
