# Generated by Django 2.0.3 on 2018-04-21 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amber', '0005_auto_20180421_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入会员日期'),
        ),
    ]
